@startuml read agency owner product

actor Agency
control server
database agency
database product

opt Read agency product
    Agency -> server: Get /products/:id, token
    activate server
    server -> server: verifyToken
    alt <font color=Red> Invalid token
        Agency <-- server: 401
    else <font color=Green> Valid token
        server -> server: isAgency
        alt <font color=Red> Is not agency
            Agency <-- server: Is not agency
        else <font color=Green> Is agency
            server -> agency: find Agency
            activate agency
            agency -> product: find Product
            activate product
            alt <font color=Red> Not found product
                agency <-- product: Product not exist
                server <-- agency: Product not exist
                Agency <-- server: 404
            else <font color=Green> Found product
                agency <-- product: Product exist
                deactivate product
                server <-- agency: Product exist
                deactivate agency
                Agency <-- server: 200
                deactivate server
            end
        end
    end
end

@enduml